org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx1G


#mod info
minecraft_version=1.21.1
neoforge_version=21.1.240
group=strhercules.chickens
tag_lanzador=NeoForge
mod_version=2.4.0
mod_id=chickens
mod_name=ModernChickens
mod_named=Modern Chickens
mod_authors= STRHercules , NadienDev , Neptune , setyczs 
mod_license=MIT
mod_description=A port of setycz's Chickens mod, and timrwood's Roost mod to 1.21.1 combined into a single package.
issues= https://github.com/NadienDev-MC-Mods/ModernChickens/issues
loader_version_range=[4,)


#mod dependencies
jei_version=19.43.0.393
wthit_version=12.10.2
jade_version=15.10.5+neoforge
au_version=1.21.1-1.4.2
ultimatefoods_version=7783056
mekanism_version=10.7.19.85
mekanism_version_range=10.7.19.85
mekanism_generators_version=10.7.19.85
mekanism_generators_version_range=10.7.19.85

# KubeJS (compile-only: the integration is loaded reflectively at runtime)
kubejs_version=2101.7.2-build.368
rhino_version=2101.2.8-build.91
